management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus, metrics
      base-path: /
      path-mapping:
        health: /health
        info: /info
        prometheus: /metrics
        metrics: /actuator/metrics

  health:
    show-details: always
    redis:
      enabled: false

server:
  port: 8080

service-response-time:
  grouped-urls:
    - http://www.mocky.io/v2/.*
    - .*/vas-service/packages.*

third-party-health-checker:
  main-status-considered: false
  endpoints:
    - name: otherservice
      url: https://ip-address/health.php
