management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus, metrics
      base-path: /
      path-mapping:
        health: s1/health
        info: s1/info
        prometheus: /metrics
        metrics: /actuator/metrics

server:
  port: 8080

service-response-time:
  grouped-urls:
    - http://www.google.com
    - http://www.mocky.io/v2/.*

